import streamlit as st
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from rag_pipeline import SiebelRAGPipeline

st.set_page_config(
    page_title="Siebel 6 Knowledge Base — RAG",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("🏢 Siebel 6 Knowledge Base — RAG Query")

st.markdown(
    "Ask questions about Oracle Siebel CRM (version 6 and later). "
    "The system retrieves relevant documentation and generates grounded answers with source citations."
)

pipeline = None

with st.sidebar:
    st.header("Configuration")
    st.markdown("**Pipeline Status**")

    try:
        pipeline = SiebelRAGPipeline()
        st.success("Pipeline initialized")
    except Exception as e:
        st.error(f"Pipeline init failed: {e}")

    st.markdown("---")
    st.markdown("**Settings**")
    top_k = st.slider("Top-K Retrieval", min_value=1, max_value=10, value=5)
    threshold = st.slider("Similarity Threshold", min_value=0.0, max_value=1.0, value=0.35, step=0.05)

    st.markdown("---")
    st.markdown("**Actions**")
    if st.button("Reset Knowledge Base"):
        if pipeline and pipeline.vector_store:
            pipeline.vector_store.reset()
            st.rerun()

    st.markdown("---")
    st.markdown("**Quick Questions**")
    quick_questions = [
        "What is Siebel CRM?",
        "How does Siebel architecture work?",
        "What are Business Components?",
        "How to configure Siebel Tools?",
        "What is the Siebel Web Architecture?",
        "How does Siebel security work?",
        "What are Siebel workflows?",
        "How to deploy Siebel CRM?",
    ]
    for q in quick_questions:
        if st.button(q, key=f"q_{q[:20]}"):
            st.session_state.question = q

if pipeline is None:
    st.error("Failed to initialize the RAG pipeline. Check that all dependencies are installed.")
    st.stop()

if pipeline.vector_store is None:
    pipeline._init_components()

if pipeline.vector_store.count() == 0:
    with st.spinner("📚 Ingesting Siebel documentation into the knowledge base... (first run only)"):
        try:
            pipeline.ingest()
            st.success(f"Knowledge base populated! {pipeline.vector_store.count()} chunks indexed.")
        except Exception as e:
            st.warning(f"Ingestion failed: {e}. You can try again later.")

query = st.text_input(
    "Ask a question about Siebel 6:",
    value=st.session_state.get("question", ""),
    placeholder="e.g., How do I configure Business Components in Siebel?",
    key="query_input",
)

if st.button("Ask", type="primary") or query:
    if not query.strip():
        st.warning("Please enter a question.")
    else:
        with st.spinner("Searching knowledge base and generating answer..."):
            result = pipeline.query(query)

        st.markdown("## Answer")
        st.markdown(result["answer"])

        st.markdown("---")
        st.markdown(f"**Sources** ({result['retrieved_count']} retrieved)")

        if result["sources"]:
            for i, src in enumerate(result["sources"], 1):
                with st.expander(f"Source {i}: {src['source']} — {src['section']}", expanded=False):
                    st.markdown(f"- **Similarity**: {src['similarity']:.4f}")
                    if src.get("url"):
                        st.markdown(f"- **URL**: {src['url']}")
        else:
            st.info("No sources found. Try rephrasing your question or run ingestion first.")

        st.markdown("---")
        with st.expander("Raw Retrieval Data", expanded=False):
            for i, src in enumerate(result["sources"], 1):
                st.json({
                    "source": src["source"],
                    "section": src["section"],
                    "url": src.get("url", ""),
                    "similarity": src["similarity"],
                })
else:
    st.info("Enter a question above or click a quick question in the sidebar to get started.")

st.markdown("---")
st.markdown(
    "⚠️ **Note**: This is a prototype. Answers are generated by an LLM and should be verified "
    "against official Oracle documentation for production use."
)